version: '3.8'

services:
  project-morkx-app:
    image: project-morkx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules  # Avoid overwriting node_modules in container
    environment:
      - NODE_ENV=development
    command: npm run start
